import { withPayload } from '@payloadcms/next/withPayload'
import type { NextConfig } from 'next'
import path from 'path'
import { fileURLToPath } from 'url'

/**
 * 301s for the old WordPress URLs, generated by `npm run wp:report`.
 * The old site has ~132 indexed URLs; without these, cutover would throw away
 * whatever search ranking they carry.
 */
import legacyRedirects from './redirects.generated.json' with { type: 'json' }
import { redirectOverrides } from './redirects.overrides'

const dirname = path.dirname(fileURLToPath(import.meta.url))

const nextConfig: NextConfig = {
  images: {
    /**
     * Declaring `localPatterns` at all turns next/image into an allowlist:
     * anything not matched here is refused outright, with a 500 rather than a
     * broken image. That is how the archdiocesan seal broke when it was added
     * under /brand — so both locations are listed.
     */
    localPatterns: [
      // Media served out of Payload's local upload handler.
      { pathname: '/api/media/file/**' },
      // Brand assets that ship with the app: the seal, taken from the old site.
      { pathname: '/brand/**' },
    ],
  },
  turbopack: {
    root: path.resolve(dirname),
  },

  async redirects() {
    // Overrides first: Next.js uses the first matching rule, and these exist
    // precisely to win against the mechanically generated mapping.
    return [...redirectOverrides, ...legacyRedirects]
  },
}

export default withPayload(nextConfig, { devBundleServerPackages: false })
