/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    deaneries: Deanery;
    parishes: Parish;
    clergy: Clergy;
    pages: Page;
    posts: Post;
    events: Event;
    categories: Category;
    verses: Verse;
    documents: Document;
    videos: Video;
    albums: Album;
    'contact-submissions': ContactSubmission;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    deaneries: DeaneriesSelect<false> | DeaneriesSelect<true>;
    parishes: ParishesSelect<false> | ParishesSelect<true>;
    clergy: ClergySelect<false> | ClergySelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    verses: VersesSelect<false> | VersesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ta') | ('en' | 'ta')[];
  globals: {
    homepage: Homepage;
    'archbishop-page': ArchbishopPage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'archbishop-page': ArchbishopPageSelect<false> | ArchbishopPageSelect<true>;
  };
  locale: 'en' | 'ta';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deaneries".
 */
export interface Deanery {
  id: number;
  name: string;
  /**
   * Used in the URL, e.g. "sacred-heart-of-jesus".
   */
  slug: string;
  /**
   * The place the deanery is seated, e.g. "Santhome". From the 2026 appointments letter.
   */
  seat?: string | null;
  /**
   * The priest currently serving as Vicar Forane (Dean). Linked automatically where the name matches a clergy record.
   */
  dean?: (number | null) | Clergy;
  /**
   * The Dean as named in the appointments letter. Kept because not every dean has a clergy record yet — the old website only published profiles for priests A–H.
   */
  deanName?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clergy".
 */
export interface Clergy {
  id: number;
  honorific: 'fr' | 'msgr' | 'mostRev' | 'rev';
  /**
   * Name without the honorific, e.g. "A. Amal Raj".
   */
  name: string;
  /**
   * URL segment, e.g. "a-amal-raj".
   */
  slug: string;
  photo?: (number | null) | Media;
  status: 'active' | 'retired' | 'away' | 'onLeave' | 'deceased';
  /**
   * Optional short biography.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Free text, e.g. "Parish Priest, St Mark's" or "Chancellor".
   */
  currentAssignment?: string | null;
  /**
   * Link to the parish, when applicable.
   */
  parish?: (number | null) | Parish;
  /**
   * Used to filter the clergy directory.
   */
  deanery?: (number | null) | Deanery;
  ordinationDate?: string | null;
  dateOfBirth?: string | null;
  languages?: ('tamil' | 'english' | 'telugu' | 'hindi' | 'malayalam' | 'latin')[] | null;
  /**
   * Previous postings. Populated automatically when transfer lists are imported.
   */
  assignmentHistory?:
    | {
        role: string;
        place?: string | null;
        from?: string | null;
        to?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Off by default. Contact details stay private unless this is ticked.
   */
  contactPublic?: boolean | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Also governed by the checkbox above -- hidden from the public site unless it is ticked.
   */
  residenceAddress?: string | null;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and for people on slow connections.
   */
  alt: string;
  /**
   * Photographer or source, if it needs crediting.
   */
  credit?: string | null;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parishes".
 */
export interface Parish {
  id: number;
  name: string;
  slug: string;
  /**
   * Patron saint or dedication.
   */
  patron?: string | null;
  deanery?: (number | null) | Deanery;
  established?: string | null;
  isShrine?: boolean | null;
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photos?: (number | Media)[] | null;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    district?: string | null;
    pincode?: string | null;
  };
  /**
   * Decimal degrees, e.g. 13.0336. Needed for the map.
   */
  latitude?: number | null;
  /**
   * e.g. 80.2699
   */
  longitude?: number | null;
  /**
   * Set automatically by the geocoder. "Approximate" shows a caveat on the parish page.
   */
  locationPrecision?: ('church' | 'locality') | null;
  phone?: string | null;
  email?: string | null;
  parishPriest?: (number | null) | Clergy;
  assistantPriests?: (number | Clergy)[] | null;
  /**
   * Loaded by npm run timings:sample to demonstrate the finder. Untick only when the timings below have been confirmed by the parish.
   */
  timingsAreSample?: boolean | null;
  services?:
    | {
        kind: 'mass' | 'novena' | 'adoration' | 'confession';
        day: 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday';
        time: string;
        language?: ('tamil' | 'english' | 'telugu' | 'hindi' | 'malayalam' | 'latin') | null;
        /**
         * Optional, e.g. "Vigil", "First Friday only", "Not during Lent".
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path, e.g. "the-bible" becomes /the-bible.
   */
  slug: string;
  /**
   * Optional, used to group pages in navigation.
   */
  parent?: (number | null) | Page;
  /**
   * Used for search results and link previews.
   */
  excerpt?: string | null;
  /**
   * If this page exists only to point at a resource on another website, put that address here.
   */
  externalUrl?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shows a notice at the top of the page in this language. Untick once a fluent speaker has checked the text.
   */
  translationNeedsReview?: boolean | null;
  /**
   * Files offered for download on this page. Drag to reorder — that is the order visitors see.
   */
  documents?: (number | Document)[] | null;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * PDFs and other files offered for download. Attach them to a page under that page’s "Documents" field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * What the download is called on the page, e.g. "Baptism Extract".
   */
  title: string;
  /**
   * Optional one-line explanation shown under the title.
   */
  description?: string | null;
  /**
   * Newsletters appear on /newsletter, grouped by year.
   */
  category?: ('form' | 'newsletter' | 'report') | null;
  /**
   * The month this issue covers.
   */
  issueDate?: string | null;
  /**
   * The language of the document itself — several forms exist in both.
   */
  language?: ('english' | 'tamil') | null;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  publishedAt?: string | null;
  categories?: (number | Category)[] | null;
  featuredImage?: (number | null) | Media;
  /**
   * Short summary used on listings and in search results.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  startDate: string;
  endDate?: string | null;
  /**
   * When ticked the times are ignored and only the date is shown.
   */
  allDay?: boolean | null;
  /**
   * e.g. "San Thome Cathedral" or "Abp's House".
   */
  location?: string | null;
  /**
   * Optional, when the event is held at one of our parishes.
   */
  parish?: (number | null) | Parish;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The homepage shows one of these each day, chosen by the date so it is the same verse for every visitor. Untick "active" to take one out of the rotation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verses".
 */
export interface Verse {
  id: number;
  /**
   * e.g. "John 15:12". Shown under the verse.
   */
  reference: string;
  /**
   * The verse itself, without the reference and without quotation marks — the page adds those.
   */
  text: string;
  /**
   * Which translation this wording comes from, e.g. "World English Bible". Shown in small print, because the archdiocese should be able to say where its scripture comes from.
   */
  translation?: string | null;
  /**
   * Include this verse in the daily rotation.
   */
  active?: boolean | null;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Videos shown on the video gallery, newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * What the video is called on the page.
   */
  title: string;
  /**
   * The id from the YouTube address — the part after "watch?v=". Pasting the whole address works too.
   */
  youtubeId: string;
  /**
   * Optional. One or two lines shown under the title.
   */
  description?: string | null;
  /**
   * The YouTube channel that published it. Shown as a credit.
   */
  channel?: string | null;
  /**
   * When the video was recorded. Videos with a date are shown first, newest first; leave it blank if it is not known.
   */
  recordedOn?: string | null;
  /**
   * The still shown before the video is played. The importer takes this from YouTube; for a new video, a frame from the video itself works well.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Sets of photographs shown on the photo gallery.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: number;
  /**
   * The occasion, e.g. "Archdiocesan Eucharistic Congress".
   */
  title: string;
  /**
   * Optional. A line or two about the occasion.
   */
  description?: string | null;
  /**
   * When it took place. Albums with a date are shown first, newest first; leave it blank if it is not known.
   */
  heldOn?: string | null;
  /**
   * The photographs, in the order they should appear. Each one needs alt text, which is set on the image itself.
   */
  photos: (number | Media)[];
  /**
   * The photograph used as the album’s tile. The first photograph is used if this is left blank.
   */
  cover?: (number | null) | Media;
  /**
   * Filled in automatically by the WordPress importer. Safe to ignore when creating new content by hand.
   */
  legacy?: {
    /**
     * WordPress post/page ID.
     */
    wpId?: number | null;
    /**
     * Original URL, for the redirect map.
     */
    url?: string | null;
    /**
     * Set by the importer when content could not be converted cleanly and a human should look at it.
     */
    needsReview?: boolean | null;
    reviewNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Messages sent through the contact form on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  status?: ('new' | 'inProgress' | 'answered' | 'spam') | null;
  name: string;
  email: string;
  phone?: string | null;
  topic?: ('general' | 'certificate' | 'mass' | 'parish' | 'website') | null;
  subject: string;
  message: string;
  /**
   * Internal notes. Not visible to the sender.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor' | 'parishPriest')[];
  /**
   * For parish priests: the parish this account may edit.
   */
  parish?: (number | null) | Parish;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'deaneries';
        value: number | Deanery;
      } | null)
    | ({
        relationTo: 'parishes';
        value: number | Parish;
      } | null)
    | ({
        relationTo: 'clergy';
        value: number | Clergy;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'verses';
        value: number | Verse;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'albums';
        value: number | Album;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deaneries_select".
 */
export interface DeaneriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  seat?: T;
  dean?: T;
  deanName?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parishes_select".
 */
export interface ParishesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  patron?: T;
  deanery?: T;
  established?: T;
  isShrine?: T;
  history?: T;
  photos?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        district?: T;
        pincode?: T;
      };
  latitude?: T;
  longitude?: T;
  locationPrecision?: T;
  phone?: T;
  email?: T;
  parishPriest?: T;
  assistantPriests?: T;
  timingsAreSample?: T;
  services?:
    | T
    | {
        kind?: T;
        day?: T;
        time?: T;
        language?: T;
        note?: T;
        id?: T;
      };
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clergy_select".
 */
export interface ClergySelect<T extends boolean = true> {
  honorific?: T;
  name?: T;
  slug?: T;
  photo?: T;
  status?: T;
  bio?: T;
  currentAssignment?: T;
  parish?: T;
  deanery?: T;
  ordinationDate?: T;
  dateOfBirth?: T;
  languages?: T;
  assignmentHistory?:
    | T
    | {
        role?: T;
        place?: T;
        from?: T;
        to?: T;
        id?: T;
      };
  contactPublic?: T;
  email?: T;
  phone?: T;
  residenceAddress?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  excerpt?: T;
  externalUrl?: T;
  content?: T;
  translationNeedsReview?: T;
  documents?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  categories?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startDate?: T;
  endDate?: T;
  allDay?: T;
  location?: T;
  parish?: T;
  description?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verses_select".
 */
export interface VersesSelect<T extends boolean = true> {
  reference?: T;
  text?: T;
  translation?: T;
  active?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  issueDate?: T;
  language?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  youtubeId?: T;
  description?: T;
  channel?: T;
  recordedOn?: T;
  thumbnail?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  heldOn?: T;
  photos?: T;
  cover?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  topic?: T;
  subject?: T;
  message?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        url?: T;
        needsReview?: T;
        reviewNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  parish?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The picture carousel and the verse of the day, as they appear on the front page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  carouselEnabled?: boolean | null;
  /**
   * Takes this many from the top of the list below, so slides can be kept ready without publishing them. Drag to reorder.
   */
  slidesToShow?: number | null;
  /**
   * Narrow screens always show one.
   */
  slidesPerView?: ('1' | '2' | '3') | null;
  /**
   * 0 turns autoplay off and leaves the arrows.
   */
  autoplaySeconds?: number | null;
  /**
   * Landscape images work best — roughly twice as wide as they are tall.
   */
  slides?:
    | {
        image: number | Media;
        /**
         * Optional. Overlaid on the image.
         */
        headline?: string | null;
        /**
         * Optional second line.
         */
        caption?: string | null;
        /**
         * Optional. A path on this site such as /archbishop, or a full https:// address.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The verses themselves are edited under Content → Verse of the day. One is chosen each day from the active ones, by date, so every visitor sees the same verse.
   */
  verseEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Archbishop’s profile, the former prelates, and the episcopal conferences. Shown at /archbishop.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archbishop-page".
 */
export interface ArchbishopPage {
  id: number;
  /**
   * Photograph shown at the top of the page.
   */
  portrait?: (number | null) | Media;
  /**
   * The label/value rows, e.g. "BORN ON" / "15th February 1952".
   */
  profile?:
    | {
        label: string;
        /**
         * One line per line of the value.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  history?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The two name-and-term lists. "Group" decides which tab a row appears under.
   */
  successions?:
    | {
        group: 'madras' | 'mylapore';
        name: string;
        term?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Archbishops of Madras–Mylapore, each with their own photograph and dates.
   */
  prelates?:
    | {
        name: string;
        image?: (number | null) | Media;
        /**
         * One date or fact per line.
         */
        details?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Each becomes a tab under "Conference" on the page.
   */
  conferences?:
    | {
        name: string;
        /**
         * The tab label, e.g. "FABC".
         */
        shortName?: string | null;
        blurb?: string | null;
        officers?:
          | {
              name: string;
              role?: string | null;
              image?: (number | null) | Media;
              fields?:
                | {
                    label: string;
                    value: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  carouselEnabled?: T;
  slidesToShow?: T;
  slidesPerView?: T;
  autoplaySeconds?: T;
  slides?:
    | T
    | {
        image?: T;
        headline?: T;
        caption?: T;
        link?: T;
        id?: T;
      };
  verseEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archbishop-page_select".
 */
export interface ArchbishopPageSelect<T extends boolean = true> {
  portrait?: T;
  profile?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  history?:
    | T
    | {
        text?: T;
        id?: T;
      };
  successions?:
    | T
    | {
        group?: T;
        name?: T;
        term?: T;
        id?: T;
      };
  prelates?:
    | T
    | {
        name?: T;
        image?: T;
        details?: T;
        id?: T;
      };
  conferences?:
    | T
    | {
        name?: T;
        shortName?: T;
        blurb?: T;
        officers?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              fields?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}